package main

const UNINITIALIZED = -1

const CONNECTED = 0
const NOT_CONNECTED = 1

const MAP_HEIGHT = 30
const MAP_WIDTH = 90

const SCRN_W = 450
const SCRN_H = 120

const ROOMS_PER_SIDE = 3

const MAX_ROOMS_NUMBER = ROOMS_PER_SIDE * ROOMS_PER_SIDE
const MAX_CORRIDORS_NUMBER = 12

const SECTOR_HEIGHT = MAP_HEIGHT / ROOMS_PER_SIDE
const SECTOR_WIDTH = MAP_WIDTH / ROOMS_PER_SIDE

const CORNER_VERT_RANGE = (SECTOR_HEIGHT - 6) / 2
const CORNER_HOR_RANGE = (SECTOR_WIDTH - 6) / 2

const ROOM_CHANCE = 0.5
const SPAWN_SET_CHANCE = 0.5

const MAX_ENEMIES_PER_ROOM = 5
const MAX_ITEMS_PER_ROOM = 3
const MAX_ENTITIES_PER_ROOM = MAX_ENEMIES_PER_ROOM + MAX_ITEMS_PER_ROOM + 2
const MAX_ENEMIES_TOTAL = MAX_ENEMIES_PER_ROOM*ROOMS_PER_SIDE*ROOMS_PER_SIDE + 2
const MAX_ITEMS_TOTAL = MAX_ITEMS_PER_ROOM*ROOMS_PER_SIDE*ROOMS_PER_SIDE + 1
const MAX_ENTITIES_TOTAL = MAX_ENEMIES_TOTAL + MAX_ITEMS_TOTAL + 2
const ENEMY_POOL_LEN = 6
const ITEM_POOL_LEN = 4

const TOP = 0
const RIGHT = 1
const BOTTOM = 2
const LEFT = 3

const LEFT_TO_RIGHT_CORRIDOR = 0
const LEFT_TURN_CORRIDOR = 1
const RIGHT_TURN_CORRIDOR = 2
const TOP_TO_BOTTOM_CORRIDOR = 3

const UNOCCUPIED = 0
const OCCUPIED = 1

const PLAYER = 0
const PLAYER_CHAR = '@'
const EXIT = 1
const EXIT_CHAR = '|'
const ENEMY = 2
const ITEM = 3

const WALL_CHAR = '#'
const CORRIDOR_CHAR = '+'
const OUTER_AREA_CHAR = '.'
const INNER_AREA_CHAR = ' '
const EMPTY_CHAR = ' '

const IS_OUTER = 0
const IS_INNER = 1
const IS_WALL = 2

const ESC = 27
const MOVEMENT_STEP = 1
const SPACE_CHAR = /*0xA0*/ ' '
const MINIMAP_WALL_CHAR = 0x2588
const MINIMAP_CORRIDOR_CHAR = /*0x2591*/ '©'
const MINIMAP_PLAYER_CHAR = /*0xA9*/ '@'
